--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/10/2020 4:01:44 p. m.
-- Server version: 5.5.5-10.4.14-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP DATABASE IF EXISTS dbreclutamiento;

CREATE DATABASE dbreclutamiento
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

--
-- Set default database
--
USE dbreclutamiento;

--
-- Create table `departamentos`
--
CREATE TABLE departamentos (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Descripcion VARCHAR(255) DEFAULT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `puestos`
--
CREATE TABLE puestos (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DepartamentoId INT(11) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  NivelRiesgo VARCHAR(5) NOT NULL,
  NivelMinimoSalario FLOAT NOT NULL,
  NivelMaximoSalario FLOAT NOT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE puestos 
  ADD CONSTRAINT FK_puestos_DepartamentoId FOREIGN KEY (DepartamentoId)
    REFERENCES departamentos(Id) ON DELETE NO ACTION;

--
-- Create table `nivel_capacitaciones`
--
CREATE TABLE nivel_capacitaciones (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Descripcion VARCHAR(255) DEFAULT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `capacitaciones`
--
CREATE TABLE capacitaciones (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  NivelId INT(11) NOT NULL,
  Descripcion VARCHAR(255) DEFAULT NULL,
  FechaDe DATETIME DEFAULT NULL,
  FechaHasta DATETIME DEFAULT NULL,
  Institucion VARCHAR(50) DEFAULT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE capacitaciones 
  ADD CONSTRAINT FK_capacitaciones_NivelId FOREIGN KEY (NivelId)
    REFERENCES nivel_capacitaciones(Id) ON DELETE NO ACTION;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Clave VARCHAR(50) NOT NULL,
  Correo VARCHAR(50) NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Apellido VARCHAR(50) NOT NULL,
  Estado VARCHAR(10) NOT NULL,
  Rol VARCHAR(15) NOT NULL,
  FechaCreacionUsuario DATETIME NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `candidatos`
--
CREATE TABLE candidatos (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DepartamentoId INT(11) NOT NULL,
  PuestoId INT(11) NOT NULL,
  UsuarioId INT(11) NOT NULL,
  SalarioAspira FLOAT DEFAULT NULL,
  RecomendadoPor VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE candidatos 
  ADD CONSTRAINT FK_candidatos_DepartamentoId FOREIGN KEY (DepartamentoId)
    REFERENCES departamentos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE candidatos 
  ADD CONSTRAINT FK_candidatos_PuestoId FOREIGN KEY (PuestoId)
    REFERENCES puestos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE candidatos 
  ADD CONSTRAINT FK_candidatos_UsuarioId FOREIGN KEY (UsuarioId)
    REFERENCES usuarios(Id) ON DELETE NO ACTION;

--
-- Create table `empleados`
--
CREATE TABLE empleados (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DepartamentoId INT(11) NOT NULL,
  PuestoId INT(11) NOT NULL,
  CandidatoId INT(11) NOT NULL,
  UsuarioId INT(11) NOT NULL,
  FechaIngreso DATETIME NOT NULL,
  Salario FLOAT NOT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE empleados 
  ADD CONSTRAINT FK_empleados_CandidatoId FOREIGN KEY (CandidatoId)
    REFERENCES candidatos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE empleados 
  ADD CONSTRAINT FK_empleados_DepartamentoId FOREIGN KEY (DepartamentoId)
    REFERENCES departamentos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE empleados 
  ADD CONSTRAINT FK_empleados_PuestoId FOREIGN KEY (PuestoId)
    REFERENCES puestos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE empleados 
  ADD CONSTRAINT FK_empleados_UsuarioId FOREIGN KEY (UsuarioId)
    REFERENCES usuarios(Id) ON DELETE NO ACTION;

--
-- Create table `candidato_experiencias_laborales`
--
CREATE TABLE candidato_experiencias_laborales (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  CandidatoId INT(11) NOT NULL,
  ExperienciaId INT(11) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE candidato_experiencias_laborales 
  ADD CONSTRAINT FK_candidato_experiencias_laborales_CandidatoId FOREIGN KEY (CandidatoId)
    REFERENCES candidatos(Id) ON DELETE NO ACTION;

--
-- Create table `candidato_capacitaciones`
--
CREATE TABLE candidato_capacitaciones (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  CandidatoId INT(11) NOT NULL,
  CapacitacionesId INT(11) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE candidato_capacitaciones 
  ADD CONSTRAINT FK_candidato_capacitaciones_CandidatoId FOREIGN KEY (CandidatoId)
    REFERENCES candidatos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE candidato_capacitaciones 
  ADD CONSTRAINT FK_candidato_capacitaciones_CapacitacionesId FOREIGN KEY (CapacitacionesId)
    REFERENCES capacitaciones(Id) ON DELETE NO ACTION;

--
-- Create table `idiomas`
--
CREATE TABLE idiomas (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(50) NOT NULL,
  Descripcion VARCHAR(255) DEFAULT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `candidato_idiomas`
--
CREATE TABLE candidato_idiomas (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  CandidatoId INT(11) NOT NULL,
  IdiomaId INT(11) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE candidato_idiomas 
  ADD CONSTRAINT FK_candidato_idiomas_CandidatoId FOREIGN KEY (CandidatoId)
    REFERENCES candidatos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE candidato_idiomas 
  ADD CONSTRAINT FK_candidato_idiomas_IdiomaId FOREIGN KEY (IdiomaId)
    REFERENCES idiomas(Id) ON DELETE NO ACTION;

--
-- Create table `competencias`
--
CREATE TABLE competencias (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Descripcion VARCHAR(255) DEFAULT NULL,
  Estado VARCHAR(10) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `candidato_competencias`
--
CREATE TABLE candidato_competencias (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  CandidatoId INT(11) NOT NULL,
  CompetenciaId INT(11) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE candidato_competencias 
  ADD CONSTRAINT FK_candidato_competencias_CandidatoId FOREIGN KEY (CandidatoId)
    REFERENCES candidatos(Id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE candidato_competencias 
  ADD CONSTRAINT FK_candidato_competencias_CompetenciaId FOREIGN KEY (CompetenciaId)
    REFERENCES competencias(Id) ON DELETE NO ACTION;

--
-- Create table `experiencias_laborales`
--
CREATE TABLE experiencias_laborales (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Empresa VARCHAR(50) DEFAULT NULL,
  PuestoOcupado VARCHAR(50) DEFAULT NULL,
  FechaDesde DATETIME DEFAULT NULL,
  FechaHasta DATETIME DEFAULT NULL,
  Salario FLOAT DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table departamentos
--
-- Table dbreclutamiento.departamentos does not contain any data (it is empty)

-- 
-- Dumping data for table nivel_capacitaciones
--
-- Table dbreclutamiento.nivel_capacitaciones does not contain any data (it is empty)

-- 
-- Dumping data for table usuarios
--
-- Table dbreclutamiento.usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table puestos
--
-- Table dbreclutamiento.puestos does not contain any data (it is empty)

-- 
-- Dumping data for table idiomas
--
-- Table dbreclutamiento.idiomas does not contain any data (it is empty)

-- 
-- Dumping data for table competencias
--
-- Table dbreclutamiento.competencias does not contain any data (it is empty)

-- 
-- Dumping data for table capacitaciones
--
-- Table dbreclutamiento.capacitaciones does not contain any data (it is empty)

-- 
-- Dumping data for table candidatos
--
-- Table dbreclutamiento.candidatos does not contain any data (it is empty)

-- 
-- Dumping data for table experiencias_laborales
--
-- Table dbreclutamiento.experiencias_laborales does not contain any data (it is empty)

-- 
-- Dumping data for table empleados
--
-- Table dbreclutamiento.empleados does not contain any data (it is empty)

-- 
-- Dumping data for table candidato_idiomas
--
-- Table dbreclutamiento.candidato_idiomas does not contain any data (it is empty)

-- 
-- Dumping data for table candidato_experiencias_laborales
--
-- Table dbreclutamiento.candidato_experiencias_laborales does not contain any data (it is empty)

-- 
-- Dumping data for table candidato_competencias
--
-- Table dbreclutamiento.candidato_competencias does not contain any data (it is empty)

-- 
-- Dumping data for table candidato_capacitaciones
--
-- Table dbreclutamiento.candidato_capacitaciones does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;